{% set name = "compas_occ" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a931d2a709b2af9ca382b69427ec3a11ca10643fc8e0ce4c81d22696aa1213b6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - compas
    - nptyping
    - typing_extensions
    - pythonocc-core

test:
  imports:
    - compas_occ

about:
  home: http://github.com/compas-dev/compas_occ
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: COMPAS wrappers for OCC
  description: |
    COMPAS OCC is a wrapper for the 3D geometry kernel of Open Cascade
    based on the Python bindings in pythonocc-core
    and with an API similar to the one of RhinoCommon.
  doc_url: http://compas.dev/compas_occ
  dev_url: https://github.com/compas-dev/compas_occ

extra:
  recipe-maintainers:
    - brgcode
    - licini
